# Generated by Django 4.0.1 on 2022-01-28 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date of overtime')),
                ('reason', models.IntegerField(blank=True, choices=[(1, 'Direct Patient Care or Theatre'), (2, 'Ward Round or Delayed/Extended handover (note, does not need pt URN)'), (3, 'Discharge Summaries or Patient Admin'), (4, 'MDM preparation')])),
                ('patientURN', models.CharField(blank=True, max_length=20)),
                ('startTime', models.TimeField(blank=True)),
                ('finishTime', models.TimeField(blank=True)),
                ('higherDutiesYN', models.CharField(blank=True, max_length=3)),
                ('preApproval', models.CharField(blank=True, max_length=200, verbose_name='NUM/Senior Registrar/Consultant Pre-Approval (not-mandatory)')),
                ('personalComment', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeNumber', models.CharField(blank=True, max_length=30)),
                ('classification', models.IntegerField(blank=True, choices=[(1, 'intern'), (2, 'HMO'), (3, 'Registrar')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintOutTimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(verbose_name='starting date')),
                ('endingDate', models.DateField(verbose_name='ending date')),
                ('linkedOvertimeRows', models.ManyToManyField(to='overtimeRecorder.OvertimeRow')),
            ],
        ),
    ]
