# Generated by Django 4.0.1 on 2022-01-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtimeRecorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='classification',
            field=models.IntegerField(blank=True, choices=[(1, 'intern'), (2, 'HMO'), (3, 'Registrar')], null=True),
        ),
    ]
