# Generated by Django 4.0.1 on 2022-01-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtimeRecorder', '0002_alter_profile_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimerow',
            name='date',
            field=models.DateField(null=True, verbose_name='date of overtime'),
        ),
        migrations.AlterField(
            model_name='overtimerow',
            name='finishTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overtimerow',
            name='higherDutiesYN',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='overtimerow',
            name='patientURN',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overtimerow',
            name='personalComment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='overtimerow',
            name='preApproval',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='NUM/Senior Registrar/Consultant Pre-Approval (not-mandatory)'),
        ),
        migrations.AlterField(
            model_name='overtimerow',
            name='reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Direct Patient Care or Theatre'), (2, 'Ward Round or Delayed/Extended handover (note, does not need pt URN)'), (3, 'Discharge Summaries or Patient Admin'), (4, 'MDM preparation')], null=True),
        ),
        migrations.AlterField(
            model_name='overtimerow',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printouttimesheet',
            name='endingDate',
            field=models.DateField(null=True, verbose_name='ending date'),
        ),
        migrations.AlterField(
            model_name='printouttimesheet',
            name='startDate',
            field=models.DateField(null=True, verbose_name='starting date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employeeNumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
