# Generated by Django 4.0.1 on 2022-01-30 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('overtimeRecorder', '0003_alter_overtimerow_date_alter_overtimerow_finishtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimerow',
            name='date',
            field=models.DateField(null=True, verbose_name='Date of overtime'),
        ),
        migrations.AlterField(
            model_name='overtimerow',
            name='finishTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Finish time'),
        ),
        migrations.AlterField(
            model_name='overtimerow',
            name='higherDutiesYN',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Higher duties performed (Y/N)'),
        ),
        migrations.AlterField(
            model_name='overtimerow',
            name='patientURN',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Patient URN'),
        ),
        migrations.AlterField(
            model_name='overtimerow',
            name='personalComment',
            field=models.TextField(blank=True, null=True, verbose_name="Personal Comment (won't be printed)"),
        ),
        migrations.AlterField(
            model_name='overtimerow',
            name='reason',
            field=models.IntegerField(blank=True, choices=[(1, 'Direct Patient Care or Theatre'), (2, 'Ward Round or Delayed/Extended handover (note, does not need pt URN)'), (3, 'Discharge Summaries or Patient Admin'), (4, 'MDM preparation')], null=True, verbose_name='Reason for overtime'),
        ),
        migrations.AlterField(
            model_name='overtimerow',
            name='startTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='classification',
            field=models.IntegerField(blank=True, choices=[(1, 'intern'), (2, 'HMO'), (3, 'Registrar')], null=True, verbose_name='job classification'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employeeNumber',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='employee number'),
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDateTime', models.DateTimeField(blank=True, null=True, verbose_name='starting date and time')),
                ('endDateTime', models.DateTimeField(blank=True, null=True, verbose_name='ending date and time')),
                ('role', models.CharField(blank=True, max_length=300, null=True, verbose_name='role performed')),
                ('job', models.CharField(blank=True, max_length=300, null=True, verbose_name='job at the time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
