# Generated by Django 4.0.1 on 2022-01-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtimeRecorder', '0004_alter_overtimerow_date_alter_overtimerow_finishtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='profile',
            name='payCycle',
            field=models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B')], null=True, verbose_name='payCycle fortnight option A or B'),
        ),
    ]
