# Generated by Django 4.0.1 on 2022-02-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtimeRecorder', '0005_profile_department_profile_paycycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='oncallTF',
            field=models.BooleanField(default=0, verbose_name='is this role on call?'),
        ),
    ]
