# Generated by Django 4.0.1 on 2022-02-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtimeRecorder', '0007_overtimerow_created_at_overtimerow_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='okToShareOvertime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='okToShareRoster',
            field=models.BooleanField(default=False),
        ),
    ]
