# Generated by Django 4.0.1 on 2022-02-16 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import overtimeRecorder.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('overtimeRecorder', '0010_alter_printouttimesheet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=overtimeRecorder.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
