# Generated by Django 4.0.1 on 2022-02-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtimeRecorder', '0011_calendarfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='okToShareOvertime',
            field=models.BooleanField(default=False, help_text='Optional: tick this box to share your overtime requests with other users of this website', verbose_name='Share overtime with other users'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='okToShareRoster',
            field=models.BooleanField(default=False, help_text='Optional: tick this box to share your roster with other users of this website', verbose_name='Share roster with other users'),
        ),
    ]
